// Product Data
const products = [
  // Electronics
  {
    id: 1,
    name: "Wireless Headphones",
    price: 79.99,
    cat: "electronics",
    img: "headphones.jpg",
    desc: "High-quality sound",
  },
  {
    id: 2,
    name: "Smartphone Stand",
    price: 24.99,
    cat: "electronics",
    img: "stand.jpg",
    desc: "Adjustable stand",
  },
  {
    id: 3,
    name: "USB-C Cable",
    price: 14.99,
    cat: "electronics",
    img: "usbc.jpg",
    desc: "Fast charging",
  },
  {
    id: 4,
    name: "Portable Charger",
    price: 49.99,
    cat: "electronics",
    img: "powerbank.jpg",
    desc: "20000mAh",
  },
  {
    id: 5,
    name: "Webcam",
    price: 59.99,
    cat: "electronics",
    img: "webcam.jpg",
    desc: "1080p video",
  },
  {
    id: 6,
    name: "Keyboard",
    price: 99.99,
    cat: "electronics",
    img: "keyboard.jpg",
    desc: "RGB lighting",
  },
  // Clothing
  {
    id: 7,
    name: "T-Shirt",
    price: 19.99,
    cat: "clothing",
    img: "tshirt.jpg",
    desc: "Cotton",
  },
  {
    id: 8,
    name: "Jeans",
    price: 49.99,
    cat: "clothing",
    img: "jeans.jpg",
    desc: "Classic fit",
  },
  {
    id: 9,
    name: "Hoodie",
    price: 54.99,
    cat: "clothing",
    img: "hoodie.jpg",
    desc: "Warm cozy",
  },
  {
    id: 10,
    name: "Sneakers",
    price: 89.99,
    cat: "clothing",
    img: "sneakers.jpg",
    desc: "Lightweight",
  },
  {
    id: 11,
    name: "Cap",
    price: 24.99,
    cat: "clothing",
    img: "cap.jpg",
    desc: "UV protect",
  },
  {
    id: 12,
    name: "Jacket",
    price: 129.99,
    cat: "clothing",
    img: "jacket.jpg",
    desc: "Waterproof",
  },
  // Home & Garden
  {
    id: 13,
    name: "Desk Lamp",
    price: 34.99,
    cat: "home",
    img: "lamp.jpg",
    desc: "USB charging",
  },
  {
    id: 14,
    name: "Coffee Maker",
    price: 89.99,
    cat: "home",
    img: "coffee-maker.jpg",
    desc: "Programmable",
  },
  {
    id: 15,
    name: "Plant Pot",
    price: 19.99,
    cat: "home",
    img: "plant-pot.jpg",
    desc: "Ceramic",
  },
  {
    id: 16,
    name: "Wall Clock",
    price: 29.99,
    cat: "home",
    img: "clock.jpg",
    desc: "Silent",
  },
  {
    id: 17,
    name: "Pillow",
    price: 24.99,
    cat: "home",
    img: "pillow.jpg",
    desc: "Soft",
  },
  {
    id: 18,
    name: "Rug",
    price: 79.99,
    cat: "home",
    img: "rug.jpg",
    desc: "Non-slip",
  },
  // Sports
  {
    id: 19,
    name: "Yoga Mat",
    price: 34.99,
    cat: "sports",
    img: "yoga-mat.jpg",
    desc: "Non-slip",
  },
  {
    id: 20,
    name: "Dumbbells",
    price: 59.99,
    cat: "sports",
    img: "dumbbells.jpg",
    desc: "5-25lbs",
  },
  {
    id: 21,
    name: "Running Shoes",
    price: 119.99,
    cat: "sports",
    img: "running-shoes.jpg",
    desc: "Cushioned",
  },
  {
    id: 22,
    name: "Water Bottle",
    price: 19.99,
    cat: "sports",
    img: "water-bottle.jpg",
    desc: "32oz",
  },
  {
    id: 23,
    name: "Bands",
    price: 29.99,
    cat: "sports",
    img: "resistance-bands.jpg",
    desc: "5 levels",
  },
  {
    id: 24,
    name: "Gym Bag",
    price: 44.99,
    cat: "sports",
    img: "gym-bag.jpg",
    desc: "Large",
  },
];